### ISSUE TITLE
update pkg/model/contantes.go when tagging a version

### ISSUE THREAD

**Issue by celinenicolas22** [Orange-OpenSource/remote-key-server#30]
constantes.go must be updated when a new version is tagged so that healthz endpoint return the right version.

**Comment by gfeun** [comment]
A simple script could help us build releases by tagging and replacing version in constantes.go:
```sh
#!/bin/sh

OLD_VERSION=${1:?}
VERSION=${2:?}

git tag "$VERSION"
sed -i -E "s/${OLD_VERSION}/${VERSION}/" ./pkg/model/constantes.go
```

To be used like this `./tag_release.sh v0.9.0 v0.10.0`
