### ISSUE TITLE
Bug in update group token

### ISSUE THREAD

**Issue by celinenicolas22** [Orange-OpenSource/remote-key-server#31]
when updating, old group token is written in vault instead of the new one

**Comment by gfeun** [comment]
Indeed, we have to replace groupToken with newGroupToken here:
https://github.com/Orange-OpenSource/remote-key-server/blob/0fb10171dd824b20ac5b892cd083ceddd99d7508/pkg/api/admin/administration.go#L624

And we should add corresponding tests
