### ISSUE TITLE
Publish rks docker image to github package registry

### ISSUE THREAD

**Issue by gfeun** [Orange-OpenSource/remote-key-server#46]
Github provides a package registry supporting Docker images. 

We can use this registry to push the image we build inside our CI to provide an easy to use RKS image

Tutorial: https://docs.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-docker-for-use-with-github-packages

Authentication inside a Github action is done by using GITHUB_TOKEN secret: https://docs.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#using-the-github_token-in-a-workflow

**Comment by celinenicolas22** [comment]
Closed by adding docker-publish.yml workflow
